
GAME_SURFACE_SIZE = (240, 180)
WINDOW_SIZE = (480, 360)
SIZE_MOD = 2

PLAYER_MASK_SIZE = (8, 8)
PLAYER_MOVEMENT_SPEED = 1

ENEMY_MASK_SIZE = (12, 12)
ENEMY_MOVEMENT_SPEED = 0.5

WAVE_SPAWN_TIMER = 240
ENEMY_WARNING_TIMER = 180

BULLET_MASK_SIZE = (8, 2)
BULLET_SPEED = 8

SHOTGUN_RPS = 2 # Revolutions Per Second
SHOTGUN_INITIAL_SPEED = 4
SHOTGUN_FULL_SPEED_TIME = 60
SHOTGUN_DECELERATION_MOD = 2
SHOTGUN_DEADLY_SPEED_THRESHOLD = 2

BACKGROUND_COLOR = (29, 43, 83)
SHOTGUN_TRACE_COLOR = (255, 0, 77)
